### PR TITLE
fix things that no work

### PR DESCRIPTION
**Pull request by xFGhoul**
fix fix fix

### CODE REVIEW

**Comment by pikaninja** [comment]
this.... what

**Comment by InterStella0** [comment]
pika, fix things please

**Comment by pikaninja** [comment]
:blobno:

**Comment by PhoenixOnARoof** [comment]
> fix fix fix

I'm not entirely sure why you wrote node.js code for a python bot. Care to explain? This PR makes zero sense

**Comment by daggy1234** [comment]
NodeModules pepepep

**Pull request closed without merging**
